### ISSUE TITLE
Add support for nvim-treesitter

### ISSUE THREAD

**Issue by EdenEast** [vv9k/bogster#2]
Thanks for the colorscheme it looks great! It would be helpful if it supported [nvim-treesitter[(https://github.com/nvim-treesitter/nvim-treesitter)

- [highlights](https://github.com/nvim-treesitter/nvim-treesitter/blob/71247a4/doc/nvim-treesitter.txt#L431)

**Comment by vv9k** [comment]
Added initial support in dfa8bfc , let me know if you have any suggestions ;)

**Comment by EdenEast** [comment]
Pull the latest changes and it works great thanks!
