### ISSUE TITLE
Error when use Airline theme

### ISSUE THREAD

**Issue by TeoDev1611** [vv9k/bogster#3]
The theme sow correctly and the airline theme too but show this error 😞 

![image](https://user-images.githubusercontent.com/73144037/119025093-64df6a00-b969-11eb-959d-e8a6022ee000.png)

Any solution?

**Comment by vv9k** [comment]
Hey! should be fixed now as of 279c7b5

**Comment by TeoDev1611** [comment]
Thanks I test this

**Comment by TeoDev1611** [comment]
Yes this solve the error thanks 👍🏽
