### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by zealotrush** [vv9k/bogster#4]
I really love this theme. However, I like using light themes during day time. Would you please make a light version?

**Comment by vv9k** [comment]
I'm glad you're enjoying it :) Sure, I'll try to come up with some initial colors today and publish a branch perhaps

**Comment by vv9k** [comment]
You can check out the branch `light`, it should contain draft light colors. I plan to test out the rough edges later on, so let me know if you find anything off ;)

**Comment by zealotrush** [comment]
![image](https://user-images.githubusercontent.com/2275580/119099674-bb23da00-ba49-11eb-95c8-0cdb9b3b7f9e.png)

Thanks! It looks great!

Personally, I find the yellow color for `Statement` is a little bit hard to see. Also, the TODO group looks like not highlighted.

**Comment by vv9k** [comment]
![image](https://user-images.githubusercontent.com/46892771/119120507-a4bb5580-ba2c-11eb-91a8-8f8e202485d8.png)

Should look better now, I also updated some groups to make more sense. Forgot to check `:help group-name` after making the theme so cheers :)

**Comment by zealotrush** [comment]
It does look better. Thanks for the quick update!
