### ISSUE TITLE
[Help wanted] Port to emacs

### ISSUE THREAD

**Issue by hashibit** [vv9k/bogster#5]
Hi, it's very beautiful theme, I love it and use it in vim and helix. Do you have plans to port to emacs too?

**Comment by vv9k** [comment]
Hi!

Thanks for the kind words! I do not have plans to port it to emacs as I don't actively use emacs and have no clue how to theme it. Any help in this issue would be appreciated.

**Comment by hashibit** [comment]
I'd like to help, but i'm not emacs expert either...XD.  sorry.

**Comment by hashibit** [comment]
hi @vv9k I managed to port to emacs using `autothemer`, suprisingly simple. the porting may be not perfect, but beautiful enough :)  

in case of others may also interested， here is the theme  [https://github.com/sekirocc/.doter/blob/master/.emacs.d/lisp/bogster-theme.el](https://github.com/sekirocc/.doter/blob/master/.emacs.d/lisp/bogster-theme.el) 


I guess i could close the issue now.
